services:
  web:
    build: .
    container_name: flixbd_app
    ports:
      - "5000:5000"
    volumes:
      - flixbd_media:/app/media
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=upload.gcloud.sbs,drivebot.gcloud.lol,72.18.215.205,localhost,upload.flixbd.xyz,*
      - CSRF_TRUSTED_ORIGINS=https://upload.gcloud.sbs,https://drivebot.gcloud.lol,http://72.18.215.205:5000,https://upload.flixbd.xyz
      - DATABASE_URL=postgresql://neondb_owner:npg_tWQqLFaU38ne@ep-super-snow-adzli05y-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
    restart: always

  worker: # Uncomment to enable qcluster task worker
    build: .
    container_name: flixbd_worker
    command: python manage.py qcluster
    volumes:
      - flixbd_media:/app/media
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://neondb_owner:npg_tWQqLFaU38ne@ep-super-snow-adzli05y-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
    restart: always

volumes:
  flixbd_media:
