# Generated by Django 6.0.3 on 2026-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='If off, pipeline skips capture (no screenshots sent to FlixBD).')),
                ('worker_base_url', models.URLField(blank=True, help_text='Worker origin, no trailing slash (e.g. https://tg-image-proxy.xxx.workers.dev)', max_length=500)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=256)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Group or user id (e.g. -1001234567890)', max_length=32)),
                ('crypto_phrase', models.CharField(default='FLixBD-image-host-crypto-v1', help_text='AES-GCM phrase; must match Worker wrangler secret CRYPTO_PHRASE', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Screenshot settings',
                'verbose_name_plural': 'Screenshot settings',
            },
        ),
    ]
