# Generated by Django 6.0.3 on 2026-03-07 05:23

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Google Config', max_length=255)),
                ('config_file', models.FileField(help_text='Upload your Google token.json or credential JSON file', upload_to='google_configs/', validators=[settings.models.validate_json_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Config',
                'verbose_name_plural': 'Google Configs',
            },
        ),
    ]
