# Generated by Django 5.2.6 on 2026-03-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Global Upload Config', max_length=100)),
                ('upload_folder_id', models.CharField(help_text='Google Drive Folder ID for uploads', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upload Settings',
                'verbose_name_plural': 'Upload Settings',
            },
        ),
        migrations.AlterField(
            model_name='googleconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
