# Generated by Django 5.2.6 on 2026-03-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_uploadsettings_alter_googleconfig_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsettings',
            name='name',
        ),
    ]
