# Generated by Django 6.0.3 on 2026-03-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_uploadsettings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsettings',
            name='worker_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of queue workers (requires qcluster restart)'),
        ),
        migrations.AlterField(
            model_name='googleconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uploadsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
