# Generated by Django 6.0.3 on 2026-03-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_uploadsettings_worker_count_alter_googleconfig_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsettings',
            name='allow_extra_resolutions',
            field=models.BooleanField(default=False, help_text='If ON, LLM can return any resolution (2160p, 520p, etc). If OFF, only 480p/720p/1080p.'),
        ),
    ]
