# Generated by Django 6.0.3 on 2026-03-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_uploadsettings_allow_extra_resolutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsettings',
            name='allow_extra_resolutions',
        ),
        migrations.AddField(
            model_name='uploadsettings',
            name='extra_res_above',
            field=models.BooleanField(default=False, help_text='Allow resolutions above 1080p (e.g. 2160p, 4K)'),
        ),
        migrations.AddField(
            model_name='uploadsettings',
            name='extra_res_below',
            field=models.BooleanField(default=False, help_text='Allow resolutions below 480p (e.g. 360p, 240p)'),
        ),
        migrations.AddField(
            model_name='uploadsettings',
            name='max_extra_resolutions',
            field=models.PositiveIntegerField(default=0, help_text='Max extra resolutions to include (0 = unlimited)'),
        ),
    ]
