# Generated by Django 6.0.3 on 2026-03-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_uploadsettings_allow_extra_resolutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsettings',
            name='extra_res_below',
            field=models.BooleanField(default=False, help_text='Allow non-standard resolutions below 720p (e.g. 520p, 360p, 240p). 480p is always included.'),
        ),
    ]
