# Generated by Django 6.0.3 on 2026-03-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_uploadsettings_extra_res_below'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlixBDSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(help_text='Base URL of the FlixBD site (e.g. https://flixbd.test)', max_length=500)),
                ('api_key', models.CharField(help_text='API key from Admin → Settings → Integrations on the FlixBD site', max_length=255)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable auto-publishing to FlixBD')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FlixBD Settings',
                'verbose_name_plural': 'FlixBD Settings',
            },
        ),
    ]
