"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7mv0lww56^csr#c!i(_3cyiq@15)2&fs9l2y+%!+hhqopq33n('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Allow large admin bulk operations (default 1000 is too low for media tasks)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://drivebot.gcloud.lol,https://upload.gcloud.sbs').split(',')

# SCRAPE_PROXY = os.environ.get('SCRAPE_PROXY', 'socks5://R.Sakib07%2F04:R.Sakib07%2F04@103.85.159.244:1088')
SCRAPE_PROXY = os.environ.get('SCRAPE_PROXY', 'socks5://sakib:sakib@103.192.158.228:1080')
GOOGLE_LLM_USE_PROXY = os.environ.get('GOOGLE_LLM_USE_PROXY', 'True').lower() in ('true', '1', 'yes')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local Apps
    'llm',
    'upload',
    'auto_up',
    'settings',
    'admin_panel',
    'credentials',

    # Third-party Apps
    'django_q',

    # django-cleanup must be last
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware", # Static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASE_URL = "postgresql://neondb_owner:npg_tWQqLFaU38ne@ep-super-snow-adzli05y-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
DATABASES = {
    'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Auth
LOGIN_URL = '/panel/login/'
LOGIN_REDIRECT_URL = '/panel/'
LOGOUT_REDIRECT_URL = '/panel/login/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Downloads directory
DOWNLOADS_DIR = BASE_DIR / 'downloads'

# Django-Q2 Queue Configuration (ORM Broker)
# Worker count is read from UploadSettings in admin panel
def _get_worker_count():
    try:
        from settings.models import UploadSettings
        s = UploadSettings.objects.first()
        return s.worker_count if s else 1
    except Exception:
        return 1

Q_CLUSTER = {
    'name': 'Upload',
    'workers': _get_worker_count(),
    'timeout': 7200,       # 2 hours max per task
    'retry': 7500,         # Retry after 2.5 hours if no result
    'queue_limit': 50,
    'bulk': 1,             # Pick 1 task at a time per worker (prevents grabbing multiple)
    'recycle': 100,        # Restart worker after 100 tasks (prevents memory leaks)
    'ack_failures': True,  # Mark failed tasks as done (don't auto-retry)
    'max_attempts': 1,     # Don't retry failed tasks
    'orm': 'default',      # Use Django ORM as broker (no Redis needed)
}

# ───────────────────────────────────────────────
# Logging Configuration (Colored & Universal)
# ───────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'colored': {
            '()': 'colorlog.ColoredFormatter',
            'format': '%(log_color)s[%(levelname)s] %(asctime)s %(name)s: %(message)s',
            'datefmt': '%H:%M:%S',
            'log_colors': {
                'DEBUG': 'cyan',
                'INFO': 'green',
                'WARNING': 'yellow',
                'ERROR': 'red',
                'CRITICAL': 'bold_red',
            },
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'colored',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # ── Our app loggers (DEBUG so all detail is visible) ──────────────────
        'upload':      {'level': 'DEBUG', 'propagate': True},
        'llm':         {'level': 'DEBUG', 'propagate': True},
        'credentials': {'level': 'DEBUG', 'propagate': True},
        'settings':    {'level': 'DEBUG', 'propagate': True},
        'auto_up':     {'level': 'DEBUG', 'propagate': True},
        'django.tasks':{'level': 'DEBUG', 'propagate': True},

        # ── Noisy third-party libs → suppress to WARNING ───────────────────────
        'httpx':                      {'level': 'WARNING', 'propagate': True},
        'pydoll':                     {'level': 'WARNING', 'propagate': True},
        'google_genai':               {'level': 'WARNING', 'propagate': True},
        'googleapiclient':            {'level': 'WARNING', 'propagate': True},
        'google_auth_httplib2':       {'level': 'WARNING', 'propagate': True},
        'django-q':                   {'level': 'WARNING', 'propagate': True},
    },
}
