# Generated by Django 6.0.3 on 2026-03-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieTask',
            new_name='MediaTask',
        ),
        migrations.AlterModelOptions(
            name='mediatask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media Task', 'verbose_name_plural': 'Media Tasks'},
        ),
        migrations.AlterModelTable(
            name='mediatask',
            table='upload_movietask',
        ),
    ]
