# Generated by Django 6.0.3 on 2026-03-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_rename_movietask_mediatask_alter_mediatask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatask',
            name='content_type',
            field=models.CharField(blank=True, choices=[('movie', 'Movie'), ('tvshow', 'TV Show')], default='', max_length=10),
        ),
    ]
