# Generated by Django 6.0.3 on 2026-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_mediatask_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatask',
            name='website_title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000),
        ),
    ]
