# Generated by Django 6.0.3 on 2026-03-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_mediatask_extra_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatask',
            name='site_content_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='ID of the published content on the target site (FlixBD). Null means not yet published.', null=True),
        ),
    ]
