# Generated by Django 6.0.3 on 2026-03-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_django_q_ormq_priority_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrmQWithPriority',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('payload', models.TextField()),
                ('lock', models.DateTimeField(null=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'django_q_ormq',
                'managed': False,
            },
        ),
    ]
