# Generated by Django 6.0.3 on 2026-03-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_ormqwithpriority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ormqwithpriority',
            options={'managed': False, 'verbose_name': 'Queued task (ORM + priority)', 'verbose_name_plural': 'Queued tasks (ORM + priority)'},
        ),
    ]
