# Generated by Django 6.0.3 on 2026-03-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_alter_ormqwithpriority_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
