# Generated by Django 5.2.6 on 2026-03-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Enter your OpenAI API Key', max_length=255)),
                ('base_url', models.URLField(default='https://api.openai.com/v1', help_text='Optional: Custom base URL for proxies or local models', max_length=255)),
                ('model_name', models.CharField(default='gpt-4o', help_text='e.g., gpt-4o, gpt-3.5-turbo', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLM Settings',
                'verbose_name_plural': 'LLM Settings',
            },
        ),
    ]
