# Generated by Django 6.0.3 on 2026-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_llmsettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Label for this config, e.g. 'OpenRouter Free'", max_length=100)),
                ('sdk', models.CharField(choices=[('openai', 'OpenAI Compatible'), ('google', 'Google Gemini'), ('mistral', 'Mistral AI')], default='openai', help_text='Which SDK to use', max_length=20)),
                ('base_url', models.CharField(blank=True, default='', help_text='API base URL (required for openai-compatible, optional for others)', max_length=500)),
                ('api_key', models.CharField(help_text='API key for this provider', max_length=500)),
                ('model_name', models.CharField(help_text='Model name, e.g. gpt-4o, gemini-2.0-flash, mistral-large-latest', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary config is tried first')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive configs are skipped')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLM Config',
                'verbose_name_plural': 'LLM Configs',
                'ordering': ['-is_primary', 'pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='llmsettings',
            options={'verbose_name': 'LLM Settings (Legacy)', 'verbose_name_plural': 'LLM Settings (Legacy)'},
        ),
        migrations.AlterField(
            model_name='llmsettings',
            name='base_url',
            field=models.URLField(default='https://api.openai.com/v1', max_length=255),
        ),
        migrations.AlterField(
            model_name='llmsettings',
            name='model_name',
            field=models.CharField(default='gpt-4o', max_length=100),
        ),
    ]
