# Generated by Django 6.0.3 on 2026-03-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_llmconfig_alter_llmsettings_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LLMSettings',
        ),
    ]
