# Generated by Django 6.0.3 on 2026-03-09 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_delete_llmsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(help_text='Snapshot of config name at call time', max_length=100)),
                ('model_name', models.CharField(help_text='Model used for this call', max_length=200)),
                ('sdk', models.CharField(help_text='SDK used (openai/google/mistral)', max_length=20)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('purpose', models.CharField(blank=True, default='', help_text='What this call was for (extract, duplicate, filename, etc.)', max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('duration_ms', models.IntegerField(default=0, help_text='Call duration in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='llm.llmconfig')),
            ],
            options={
                'verbose_name': 'LLM Usage',
                'verbose_name_plural': 'LLM Usage',
                'ordering': ['-created_at'],
            },
        ),
    ]
