# Generated by Django 6.0.4 on 2026-04-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0012_llmusage_search_query_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmusage',
            name='duplicate_check_json',
            field=models.TextField(blank=True, default='', help_text='extract+dup_check: duplicate_check object from the model output. Other purposes: usually empty (full request is in outbound_request_json).'),
        ),
        migrations.AlterField(
            model_name='llmusage',
            name='duplicate_context_json',
            field=models.TextField(blank=True, default='', help_text='extract+dup_check: DB candidates + target-site rows for that prompt. auto_filter: per-URL local db_results + FlixBD rows (auto_filter_db_and_flixbd_by_item).'),
        ),
    ]
