# Generated by Django 6.0.3 on 2026-03-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('total_scraped', models.PositiveIntegerField(default=0, help_text='Total entries found on homepage')),
                ('url_skipped', models.PositiveIntegerField(default=0, help_text='Skipped because URL already in MediaTask')),
                ('daily_limit_skipped', models.PositiveIntegerField(default=0, help_text='Skipped because already processed today')),
                ('llm_approved', models.PositiveIntegerField(default=0, help_text='Approved by LLM for processing')),
                ('llm_skipped', models.PositiveIntegerField(default=0, help_text='Skipped by LLM decision')),
                ('queued', models.PositiveIntegerField(default=0, help_text='Actually queued for processing')),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scrape Run',
                'verbose_name_plural': 'Scrape Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_title', models.CharField(max_length=500)),
                ('clean_name', models.CharField(blank=True, default='', max_length=500)),
                ('year', models.CharField(blank=True, default='', max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('action', models.CharField(choices=[('process', 'Queued for Processing'), ('skip_url_exists', 'Skipped — URL already in DB'), ('skip_daily_limit', 'Skipped — Daily limit reached'), ('skip_llm', 'Skipped — LLM decision'), ('skip_race', 'Skipped — Race condition'), ('skip_no_title', 'Skipped — No title extracted')], max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('llm_priority', models.CharField(blank=True, default='', max_length=10)),
                ('media_task_pk', models.IntegerField(blank=True, help_text='PK of created MediaTask if queued', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auto_up.scraperun')),
            ],
            options={
                'verbose_name': 'Scrape Item',
                'verbose_name_plural': 'Scrape Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['url', 'action', 'created_at'], name='auto_up_scr_url_c65d27_idx')],
            },
        ),
    ]
