# Generated by Django migration (manual)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperun',
            name='skip_list_skipped',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Skipped because URL is in the manual auto-up skip list',
            ),
        ),
        migrations.AlterField(
            model_name='scrapeitem',
            name='action',
            field=models.CharField(
                choices=[
                    ('process', 'Queued for Processing'),
                    ('skip_url_exists', 'Skipped — URL already in DB'),
                    ('skip_daily_limit', 'Skipped — Daily limit reached'),
                    ('skip_llm', 'Skipped — LLM decision'),
                    ('skip_race', 'Skipped — Race condition'),
                    ('skip_no_title', 'Skipped — No title extracted'),
                    ('skip_skip_list', 'Skipped — URL in manual skip list'),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='AutoUpSkipUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Full page URL to skip during auto-up scrapes', max_length=500)),
                (
                    'normalized_url',
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text='Canonical form used for matching (set automatically)',
                        max_length=600,
                        unique=True,
                    ),
                ),
                (
                    'note',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Optional note (why this URL is skipped)',
                        max_length=300,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto-up skip URL',
                'verbose_name_plural': 'Auto-up skip URLs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
